app:
    base:
        url: http://universities.hipolabs.com/search
spring:
    application:
        name: university-app
server:
    port: 8090

student:
    app:
        base:
            url: https://crudcrud.com/api/0883367724e5480da0be7066a94f3bb0/students